<%@ Page Title="Schedules" Language="C#" MasterPageFile="~/Views/Master/Site.Master" AutoEventWireup="true" CodeBehind="Schedules.aspx.cs" Inherits="SkyAirline.Views.Schedule.Schedules" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <asp:HyperLink NavigateUrl="~/Views/Schedule/AddSchedule" Text="Add New Flight Schedule" runat="server" CssClass="btn btn-primary"/>
    <asp:GridView runat="server" ID="schedulesGrid"
        ItemType="SkyAirline.Models.Schedule" DataKeyNames="ScheduleID" 
        SelectMethod="GetSchedules" UpdateMethod="UpdateSchedule" OnRowDataBound="RowDataBound"
        DeleteMethod="DeleteSchedule" AllowSorting="true" AllowPaging="true" PageSize="4"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateColumns="false"
        OnCallingDataMethods="schedulesGrid_CallingDataMethods" CssClass="container table table-success table-striped" 
        AutoGenerateSelectButton="true" RowStyle-CssClass="table-primary">
        <Columns>
            <asp:DynamicField DataField="ScheduleID" ItemStyle-CssClass="table-primary" />
            <asp:TemplateField HeaderText="Flight Number">
              <ItemTemplate>
                <asp:Label Text="<%# Item.Flight.FlightNumber %>" runat="server" />
              </ItemTemplate>              
              <EditItemTemplate>
                <asp:DropDownList ID="ddlFlights" runat="server"/>
              </EditItemTemplate>
            </asp:TemplateField>               
            <asp:DynamicField DataField="DepartureDate" ItemStyle-CssClass="table-primary" />
            <asp:DynamicField DataField="ArrivalDate" ItemStyle-CssClass="table-primary" />
            <asp:DynamicField DataField="EconomyClassFare" ItemStyle-CssClass="table-primary" />
            <asp:DynamicField DataField="BusinessClassFare" ItemStyle-CssClass="table-primary" />
            <asp:TemplateField HeaderText="Available Economy Seats">
              <ItemTemplate>
                <asp:Label Text="<%# Item.AvailableEconomyClassSeats %>" runat="server" />
              </ItemTemplate> 
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Available Business Seats">
              <ItemTemplate>
                <asp:Label Text="<%# Item.AvailableBusinessClassSeats %>" runat="server" />
              </ItemTemplate> 
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
