<%@ Page Title="Airports" Language="C#" MasterPageFile="~/Views/Master/Site.Master" AutoEventWireup="true" CodeBehind="Airports.aspx.cs" Inherits="SkyAirline.Views.Airport.Airports" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <asp:HyperLink NavigateUrl="~/Views/Airport/AddAirport" Text="Add New Airport" runat="server" CssClass="btn btn-primary"/>
    <asp:GridView runat="server" ID="citiesGrid"
        ItemType="SkyAirline.Models.Airport" DataKeyNames="AirportID" 
        SelectMethod="GetAirports" UpdateMethod="UpdateAirport" OnRowDataBound="RowDataBound"
        DeleteMethod="DeleteAirport" AllowSorting="true" AllowPaging="true" PageSize="4"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateColumns="false"
        OnCallingDataMethods="airportsGrid_CallingDataMethods" CssClass="container table table-success table-striped" RowStyle-CssClass="table-primary">
        <Columns>
            <asp:DynamicField DataField="AirportID" ItemStyle-CssClass="table-primary" />
            <asp:DynamicField DataField="AirportCode" ItemStyle-CssClass="table-primary" />
            <asp:TemplateField HeaderText="City Name">
              <ItemTemplate>
                <asp:Label Text="<%# Item.AirportLocation.CityName %>" runat="server" />
              </ItemTemplate>              
              <EditItemTemplate>
                <asp:DropDownList ID="ddlCities" runat="server"/>
              </EditItemTemplate>
            </asp:TemplateField>  
            <asp:TemplateField HeaderText="Country">
              <ItemTemplate>
                <asp:Label Text="<%# Item.AirportLocation.Country %>" runat="server" />
              </ItemTemplate>
            </asp:TemplateField> 
        </Columns>
    </asp:GridView>
</asp:Content>
