<%@ Page Title="City" Language="C#" MasterPageFile="~/Views/Master/Site.Master" AutoEventWireup="true" CodeBehind="Cities.aspx.cs" Inherits="SkyAirline.Views.City.Cities" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <asp:HyperLink NavigateUrl="~/Views/City/AddCity" Text="Add New City" runat="server" CssClass="btn btn-primary"/>
    <asp:GridView runat="server" ID="citiesGrid"
        ItemType="SkyAirline.Models.City" DataKeyNames="CityID" 
        SelectMethod="GetCities" UpdateMethod="UpdateCity"
        DeleteMethod="DeleteStudent" AllowSorting="true" AllowPaging="true" PageSize="4"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateColumns="false"
        OnCallingDataMethods="citiesGrid_CallingDataMethods" CssClass="container table table-success table-striped" RowStyle-CssClass="table-primary">
        <Columns>
            <asp:DynamicField DataField="CityID" ItemStyle-CssClass="table-primary" />
            <asp:DynamicField DataField="CityName" ItemStyle-CssClass="table-primary" />
            <asp:DynamicField DataField="Country" ItemStyle-CssClass="table-primary" />          
        </Columns>
    </asp:GridView>
</asp:Content>
