<%@ Page Title="Flights" Language="C#" MasterPageFile="~/Views/Master/Site.Master" AutoEventWireup="true" CodeBehind="Flights.aspx.cs" Inherits="SkyAirline.Views.Flight.Flights" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <asp:HyperLink NavigateUrl="~/Views/Flight/AddFlight" Text="Add New Flight" runat="server" CssClass="btn btn-primary"/>
    <asp:GridView runat="server" ID="flightsGrid"
        ItemType="SkyAirline.Models.Flight" DataKeyNames="FlightID" 
        SelectMethod="GetFlights" UpdateMethod="UpdateFlight" OnRowDataBound="RowDataBound"
        DeleteMethod="DeleteFlight" AllowSorting="true" AllowPaging="true" PageSize="4"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateColumns="false"
        OnCallingDataMethods="flightsGrid_CallingDataMethods" CssClass="container table table-success table-striped" 
        AutoGenerateSelectButton="true" RowStyle-CssClass="table-primary">
        <Columns>
            <asp:DynamicField DataField="FlightID" ItemStyle-CssClass="table-primary" />
            <asp:DynamicField DataField="FlightNumber" ItemStyle-CssClass="table-primary" />
            <asp:TemplateField HeaderText="Departure Location">
              <ItemTemplate>
                <asp:Label Text="<%# Item.Departure.Location() %>" runat="server" />
              </ItemTemplate>              
              <EditItemTemplate>
                <asp:DropDownList ID="ddlDapartureAirports" runat="server"/>
              </EditItemTemplate>
            </asp:TemplateField>  
            <asp:TemplateField HeaderText="Arrival Location">
              <ItemTemplate>
                <asp:Label Text="<%# Item.Arrival.Location() %>" runat="server" />
              </ItemTemplate>
              <EditItemTemplate>
                <asp:DropDownList ID="ddlArrivalAirports" runat="server"/>
              </EditItemTemplate>
            </asp:TemplateField>
            <asp:DynamicField DataField="EconomyClassSeats" ItemStyle-CssClass="table-primary" />
            <asp:DynamicField DataField="BusinessClassSeats" ItemStyle-CssClass="table-primary" />
        </Columns>
    </asp:GridView>

</asp:Content>
